# **Pytorch Fundamentals**

>[Pytorch Fundamentals](#scrollTo=4NvBa2ArHcxy)

>>[Introduction to Tensor](#scrollTo=IJ63STuYvO7o)

>>>[Scalar](#scrollTo=nurFriQdCgMz)

>>>[Vector](#scrollTo=C0jtR0K0CjyR)

>>>[Matrix](#scrollTo=CDGhya2GCm53)

>>>[Tensor](#scrollTo=dpAmfYcUCp3S)

>>[Random tensors](#scrollTo=k3LKg7f7mRVT)



In [12]:
#import essential libaries
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [13]:
#command for checking Pytorch and cuda version
torch.__version__

'2.1.0+cu121'

from above result, now, we use
- Pytorch in the version of 2.1.0
- cuda in the version of 12.1

## **Introduction to Tensor**

Pytorch tensors are created using

```
torch.Tensor()
```
- A [torch.Tensor()](https://pytorch.org/docs/stable/tensors.html) is a multi-dimensional matrix containing elements of a single data type

- **torch.Tensor** is an alias for the default tensor **type  torch.FloatTensor** (32-bit floating point for CPU tensor)



### **Scalar**

In [14]:
#create tensors
scalar = torch.tensor(7)
scalar

tensor(7)

In [15]:
#to check number of dimensions of tensors
scalar.ndim

0

In [16]:
#to get tensor back as Python int
scalar.item()

7

In [17]:
scalar.shape

torch.Size([])

### **Vector**

In [18]:
#Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [19]:
vector.ndim

1

In [20]:
vector.shape

torch.Size([2])

**easily to remember**: number of dimension = number of [ ] or number of element result from .shape

In [21]:
#number of element
vector.shape

torch.Size([2])

### **Matrix**

In [22]:
#matrix
MATRIX = torch.tensor([[7, 8],
                      [9, 10]])

MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [23]:
MATRIX.ndim
#2 square brackets

2

In [24]:
MATRIX[0]

tensor([7, 8])

In [25]:
MATRIX[1]

tensor([ 9, 10])

In [26]:
MATRIX.shape
#2x2

torch.Size([2, 2])

### **Tensor**

In [27]:
TENSOR = torch.tensor([[[1, 2, 3],
                      [3, 6, 9],
                      [2, 4, 4]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 4]]])

In [28]:
TENSOR.ndim

3

In [29]:
TENSOR.shape

torch.Size([1, 3, 3])

tensors pic

[source](https://hkilter.com/index.php?title=What_is_Tensor%3F)

## **Random tensors**

Many neural networks learn things by starting with these following steps:

1. random number in the tensors with [
torch.rand](https://pytorch.org/docs/stable/generated/torch.rand.html)
2. look at data
3. update random numbers
4. look at data
5. update random numbers


In [ ]:
#create a random tensor of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.6714, 0.8849, 0.6440, 0.7490],
        [0.2665, 0.2235, 0.8685, 0.5451],
        [0.7917, 0.0917, 0.4951, 0.1320]])

In [ ]:
random_tensor.ndim
#number of bracket

2

In [ ]:
random_tensor = torch.rand(3,3,4) #(number of channels/size of the third dimentions (number of bracket for easy noticing), rows of each matrix, columns of each matrix)
random_tensor

tensor([[[0.8392, 0.2026, 0.3443, 0.3889],
         [0.4184, 0.2061, 0.5102, 0.7971],
         [0.9066, 0.4758, 0.8494, 0.1696]],

        [[0.2988, 0.3745, 0.1139, 0.7772],
         [0.9042, 0.8952, 0.4544, 0.4371],
         [0.5692, 0.0865, 0.8937, 0.6553]],

        [[0.2144, 0.8869, 0.4258, 0.6195],
         [0.6845, 0.8133, 0.3455, 0.7764],
         [0.2148, 0.8847, 0.7957, 0.7891]]])

In [ ]:
random_tensor.ndim

3

In [ ]:
random_tensor.shape #size of tensors

torch.Size([3, 3, 4])

In [ ]:
#create a random number tensor with similar shape to an image
