# **Pytorch Fundamentals**

>[Pytorch Fundamentals](#scrollTo=ZOLPVer6Ct1p)

>>[Introduction to Tensor](#scrollTo=IJ63STuYvO7o)

>>>[Scalar](#scrollTo=nurFriQdCgMz)

>>>[Vector](#scrollTo=C0jtR0K0CjyR)

>>>[Matrix](#scrollTo=CDGhya2GCm53)

>>>[Tensor](#scrollTo=dpAmfYcUCp3S)



In [2]:
#import essential libaries
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
#command for checking Pytorch and cuda version
torch.__version__

'2.1.0+cu121'

from above result, now, we use
- Pytorch in the version of 2.1.0
- cuda in the version of 12.1

## **Introduction to Tensor**

Pytorch tensors are created using

```
torch.Tensor()
```
- A [torch.Tensor()](https://pytorch.org/docs/stable/tensors.html) is a multi-dimensional matrix containing elements of a single data type

- **torch.Tensor** is an alias for the default tensor **type  torch.FloatTensor** (32-bit floating point for CPU tensor)



### **Scalar**

In [4]:
#create tensors
scalar = torch.tensor(7)
scalar

tensor(7)

In [5]:
#to check number of dimensions of tensors
scalar.ndim

0

In [6]:
#to get tensor back as Python int
scalar.item()

7

### **Vector**

In [7]:
#Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [8]:
vector.ndim

1

**easily to remember**: number of dimension = number of [ ]

In [9]:
#number of element
vector.shape

torch.Size([2])

### **Matrix**

In [10]:
#matrix
matrix = torch.tensor([[7, 8],
                      [9, 10]])

matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [11]:
matrix.ndim
#2 square brackets

2

In [12]:
matrix[0]

tensor([7, 8])

In [13]:
matrix[1]

tensor([ 9, 10])

In [14]:
matrix.shape
#2x2

torch.Size([2, 2])

### **Tensor**

In [15]:
tensor = torch.tensor([[[1, 2, 3],
                      [3, 6, 9],
                      [2, 4, 4]]])
tensor

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 4]]])

In [16]:
tensor.ndim

3

In [17]:
tensor.shape

torch.Size([1, 3, 3])